### ISSUE TITLE
Upload Table Name Issue With Custom Prefixes

### ISSUE THREAD

**Issue by kstover** [wpninjas/ninja-forms-uploads#263]
When activating the plugin on an install with a non-standard wp_ prefix, the ninja_forms_uploads table is created without a prefix.

**Comment by polevaultweb** [comment]
@kstover what version of NF core? I've got it installed with non standard prefix.

**Comment by polevaultweb** [comment]
This is actually happening to users! https://wpninjas.kustomerapp.com/app/customers/5963e9b7efc6710010f5b010/event/5963e9b701fc550010f7749e

**Comment by polevaultweb** [comment]
Core changed that caused it, as FU uses the migration class https://github.com/wpninjas/ninja-forms/commit/74ba12c869d426b0fd0e02bfeae18252f7790b00 cc @kjohnson :)
