### ISSUE TITLE
Control the FU data sent to Zapier when using External uploads

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms-uploads#281]
@fatcatappsdev we need to chat if there is a filter on the Zapier end that FU can hook into.

From https://wpninjas.kustomerapp.com/app/customers/598158988b8bba0010269970/event/5981589818dfbd00114bddcb

**Comment by fatcat-jeremy** [comment]
@polevaultweb 

I'll have Ryan ( @fatcatappsdev ) to get back to you on this soon. I wanted to download and install a copy of the file uploads extension, so I can test it out, and have clear understanding of the issue.

If it's ok that I grab it from here, what branch or tag would be best? Let me know, and I'll take a look, and see what the best way to go about this is.

**Comment by polevaultweb** [comment]
hey @fatcat-jeremy, great - latest release is good - https://github.com/wpninjas/ninja-forms-uploads/releases/tag/v3.0.12

**Comment by fatcat-jeremy** [comment]
@polevaultweb James with NF was asking us if this issue was resolved in the latest release of NF, and I was not sure. Did you figure something out without us?

If not, we'll have our developer available to assist next week. We had to sort this into our roadmap, so he'll be able to get back to you soon.

**Comment by polevaultweb** [comment]
@fatcat-jeremy nope, nothing added to FU. I was waiting to hear from you as per https://github.com/wpninjas/ninja-forms-uploads/issues/281#issuecomment-321197400

**Comment by fatcatappsdev** [comment]
I had a chance to review the issue and I think there are two ways we could solve it:

1 - In File Uploads plugin populate the 'external_path', which we can then pick off in our process action, and send along to Zapier

![image](https://user-images.githubusercontent.com/16645599/29560239-8eec1206-875b-11e7-814e-4db32291bc72.png)

or

2 - Implement this https://github.com/wpninjas/ninja-forms-uploads/issues/6 -- assuming the URL would be the external URL, if the user is using that option

**Comment by polevaultweb** [comment]
@fatcatappsdev How late does the zapier action happen? Perhaps it is hitting to early before external upload.

**Comment by fatcatappsdev** [comment]
It's priority 10 & timing is 'late', I tried various other timings & priority and still haven't had that field be populated, maybe im doing something wrong

**Comment by fatcat-jeremy** [comment]
@polevaultweb 

Any update on this issue? Do you think either of the above suggestions are doable, or is there something more we would need to do for you within our plugin? Or did you have any questions for our lead dev?

If you think those are workable, any idea on a time-frame?

Let me know, thanks.

**Comment by polevaultweb** [comment]
@fatcat-jeremy hey, will be looking later today
