### ISSUE TITLE
Isn't this a paid plugin?

### ISSUE THREAD

**Issue by HardeepAsrani** [wpninjas/ninja-forms-uploads#296]
Just out of curiosity, why do you have your paid extensions in a public repository? :)

**Comment by HardeepAsrani** [comment]
Duplicate of: https://github.com/wpninjas/ninja-forms-uploads/issues/296

**Comment by wpnzach** [comment]
Shh, it's a secret!  ;) We're experimenting at the moment, for a variety of reasons.  We had a lot of users getting our addons from "resellers" where we can't guarantee safety or quality.  For those more advanced users, we're hoping they find this instead to keep them safe.  If they're determined to get it for cheap or free, they will...we just want them to be safe regardless.  Having these repos public also allows our more technical users to interact with us here and submit bug reports or even pull requests, helping us to make a better product.

In the past, some users would want to modify one of our addons but that modification would obviously get overwritten when we pushed an update.  This allows those users to submit their modifications here if they're not to specific for consideration in a wider release.

It's not something we advertise or are interested in advertising at the moment...we're just testing to see if the pros of openness outweight the cons we might face in things like lost sales.

**Comment by jameslaws** [comment]
Support and automatic updates would still require an active paid license.

**Comment by HardeepAsrani** [comment]
Now I now I can sell latest version of your paid plugins. XD

Jokes apart, seems like a great idea. Would love to see how it works out. If someone wants to get it for free, they won't buy anyway so it's better to at least grow user base with them. :)
