### ISSUE TITLE
Disable Save to Server and attach file upload not working...

### ISSUE THREAD

**Issue by ericwindham** [wpninjas/ninja-forms-uploads#305]
Add a file upload to form
Disable 'Save To Server' for the file upload field
In Email Action, add file upload as an attachment.

Result:

The email adds a link to the uploaded file which resolves to a 404 error(b/c we're not saving it to the server), and the file isn't being attached to the email.

**Comment by polevaultweb** [comment]
Hi @ericwindham thanks for the bug report.

I've just tried to recreate, and as yes any links to File Uploads fields will 404 for files not saved to server. That is correct.

However, I couldn't recreate the bug of the attachment not working. Can you edit your `wp-config.php` file to replace

```
define('WP_DEBUG', false);
```

with 

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

And then retry the process again. Any errors will be caught in `wp-content/debug.log`

**Comment by Much2tall** [comment]
@ericwindham 

My results are the same as those of @polevaultweb.

The 404 happens if I click on the link in the message. However, the attachment appears to be working correctly.

**Comment by ericwindham** [comment]
So yes, I jumped the gun on this. The 404 thing does happen, but the attachment is there. MailHog doesn't show the attachment in HTML mode, but I can see the attachment in plain text, source, and MIME modes. I'll get back with the customer and see if I can figure out the issue.

**Comment by ericwindham** [comment]
Do we want to close this issue? Or leave it open for the 404 thing? Open separate issue for the 404 thing?

**Comment by Much2tall** [comment]
File Uploads should probably remove its merge tag from the {fields_table} and {all_fields_table} merge tags if "Save to Server" is disabled for the upload.

So, that portion, I would still consider a bug.

**Comment by polevaultweb** [comment]
@Much2tall can you raise as a separate issue please.
