### ISSUE TITLE
Translating "select_files_text"

### ISSUE THREAD

**Issue by jonnymaceachern** [wpninjas/ninja-forms-uploads#309]
I'm using the `ninja_forms_localize_fields` hook to translate form fields. It will let me modify labels, but when attempting to modify the File Uploads button text, it remains as the default "Select Files".

```php

function translate_ninja_forms_fields( $field ) {

        // This lets me successfully modify the label
	$field['settings']['label'] = "test";

        // This fails to modify the button text
	$field['settings']['select_files_text'] = "test";

	return $field;
}

add_filter( 'ninja_forms_localize_fields', 'ninja_forms_localize_fields', 10, 1 );
```

**Comment by polevaultweb** [comment]
@jonnymaceachern that filter is just for core NF strings. On the current version you can use the filter `ninja_forms_uploads_js_strings` and in future versions use `ninja_forms_upload_select_files_text`. Or you can translate the .pot file with your language of choice.
