### ISSUE TITLE
Not working on Mobile Devices

### ISSUE THREAD

**Issue by jleesmith** [wpninjas/ninja-forms-uploads#328]
Functions properly on desktops. 👍 

Mobile: 👎 
You can select files to upload, but no response after selecting file.
The progress bar sometimes activates, but no completion, and no files in the uploads/ninja-forms/tmp folder. 
Ninja Forms Version 3.2.18
Used different options of saving media, attaching to email, external saving, etc.

**Comment by wpnzach** [comment]
@jleesmith can you submit a support request here: https://ninjaforms.com/contact/?

I can't replicate any problems on mobile, so I think this is most likely related to your environment or setup in some way.  Our support team should be able to help you sort whatever is going on.

**Comment by WolNielsen** [comment]
I am having the same issue, forms not working on Andriod (S9), but they are working on iphone
