### ISSUE TITLE
$files['name'] count

### ISSUE THREAD

**Issue by Rozkalns** [wpninjas/ninja-forms-uploads#339]
It does not make sense to [count string](https://github.com/wpninjas/ninja-forms-uploads/blob/develop/includes/ajax/controllers/uploads.php#L73), it's impossible. Solution would be just `count ( $files )`.

As we can see in [PHP documentation](http://php.net/manual/en/features.file-upload.post-method.php), `$_FILES['userfile']['name']` will contain string.

Also, it gives an warning to all uploads:

```PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/wp-content/plugins/ninja-forms-uploads/includes/ajax/controllers/uploads.php on line 74```

**Comment by polevaultweb** [comment]
This has been fixed
