### ISSUE TITLE
How to remove the progress bar?

### ISSUE THREAD

**Issue by mntsikou** [wpninjas/ninja-forms-uploads#342]
Hi team,

This is my first post on github and I hope my request is precise enough.

I am working on my website and I am using the WP Ninja Forms File Upload Plugin. 
I am looking to remove the progress bar to integrate the form layout to my website.

Any tips?

**Comment by polevaultweb** [comment]
@mntsikou you can add this CSS to your theme:

```
.nf-fu-progress { display: none; }
```

**Comment by mntsikou** [comment]
Thank you!
